Force more permissive linking.
When testing the bdd_dict example here:
    https://spot.lre.epita.fr/tut90.html
I got a linking error:
    /usr/bin/ld: hoax.p/src_main2.cpp.o: undefined reference to symbol 'bdd_delref_nc'
    /usr/bin/ld: /usr/local/lib/libbddx.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
so more permissive library ordering in the
 linking step was added just to make
 my life easier. I'm here to do parity
 stuff, not wrangle a compiler/linker.